spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

logging:
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
  level:
    root: info

app:
  certs:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem
